// Generated by CoffeeScript 1.4.0
(function() {
    var NunjucksCompiler, fs, nunjucks, sysPath;

    fs = require("fs");

    nunjucks = require('nunjucks');

    sysPath = require('path');

    module.exports = NunjucksCompiler = (function() {

        function NunjucksCompiler() {}

        NunjucksCompiler.prototype.brunchPlugin = true;

        NunjucksCompiler.prototype.type = 'template';

        NunjucksCompiler.prototype.extension = 'html';

        NunjucksCompiler.prototype.pattern = /(\.(html|njs))$/;

        NunjucksCompiler.prototype.compile = function(data, path, callback) {
            var error, filename, result;
            try {
                return result = "module.exports = "+nunjucks.precompile(path, {asFunction: true})+"";
            } catch (err) {
                return error = err;
            } finally {
                callback(error, result);
            }
        };

        return NunjucksCompiler;

    })();

}).call(this);
