// Generated by CoffeeScript 1.4.0
(function() {
    var NunjucksCompiler, fs, swig, sysPath;

    fs = require("fs");

    swig = require('swig');

    sysPath = require('path');

    module.exports = NunjucksCompiler = (function() {

        function NunjucksCompiler() {}

        NunjucksCompiler.prototype.brunchPlugin = true;

        NunjucksCompiler.prototype.type = 'template';

        NunjucksCompiler.prototype.extension = 'html';

        NunjucksCompiler.prototype.pattern = /(\.(html|njs))$/;

        NunjucksCompiler.prototype.compile = function(data, path, callback) {
            var error, filename, result;
            try {
                filename = sysPath.basename(path).split(".")[0];
                return result = "module.exports = nunjucks.compile(" + (JSON.stringify(data)) + ", { filename: '" + filename + "'});";
            } catch (err) {
                return error = err;
            } finally {
                callback(error, result);
            }
        };

        NunjucksCompiler.prototype.include = [sysPath.join(__dirname, '..', 'vendor', 'nunjucks.min.js')];

        return NunjucksCompiler;

    })();

}).call(this);
